//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnetpasshashhistory
    {
        public int Id { get; set; }
        public string aspnetuserId { get; set; }
        public string PasswordHash { get; set; }
        public System.DateTime passwordcreated_at { get; set; }
        public System.DateTime passwordexpire_at { get; set; }
        public int password_valid_days { get; set; }
    }
}
