//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_preferences
    {
        public int id { get; set; }
        public string user_email { get; set; }
        public string bank { get; set; }
        public string account_number { get; set; }
        public string account_type { get; set; }
        public string account_holder { get; set; }
    }
}
