//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cca12months
    {
        public int ID { get; set; }
        public Nullable<int> SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string EnquiriesByClient { get; set; }
        public string EnquiriesByOther { get; set; }
        public string PositiveLoans { get; set; }
        public string HighestMonthsInArrears { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
