//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_list
    {
        public int id { get; set; }
        public Nullable<int> checks_id { get; set; }
        public string checks { get; set; }
        public string detail_attached_file_name { get; set; }
        public string results { get; set; }
        public string summary { get; set; }
    }
}
