//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check
    {
        public int id { get; set; }
        public System.DateTime search_date { get; set; }
        public Nullable<int> check_id { get; set; }
        public string first_name { get; set; }
        public string maiden_name { get; set; }
        public string surname { get; set; }
        public string IDNum { get; set; }
        public string passportNum { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int mobile { get; set; }
        public Nullable<int> Num_search { get; set; }
        public string reason { get; set; }
        public string consent_Form { get; set; }
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string status { get; set; }
        public string complete_date { get; set; }
        public string checks { get; set; }
        public string results { get; set; }
        public string summary { get; set; }
    }
}
