//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumerstatistic
    {
        public int ID { get; set; }
        public string SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string HighestJudgment { get; set; }
        public string RevolvingAccounts { get; set; }
        public string InstalmentAccounts { get; set; }
        public string OpenAccounts { get; set; }
        public string AdverseAccounts { get; set; }
        public string Percent0ArrearsLast12Histories { get; set; }
        public string MonthsOldestOpenedPPSEver { get; set; }
        public string NumberPPSLast12Months { get; set; }
        public string NLRMicroloansPast12Months { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
