//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpa_accounts
    {
        public int ID { get; set; }
        public string SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string Account_ID { get; set; }
        public string SubscriberCode { get; set; }
        public string SubscriberName { get; set; }
        public string AccountNO { get; set; }
        public string SubAccountNO { get; set; }
        public string OwnershipType { get; set; }
        public string OwnershipTypeDescription { get; set; }
        public string Reason { get; set; }
        public string ReasonDescription { get; set; }
        public string PaymentType { get; set; }
        public string PaymentTypeDescription { get; set; }
        public string AccountType { get; set; }
        public string AccountTypeDescription { get; set; }
        public string OpenDate { get; set; }
        public string DeferredPaymentDate { get; set; }
        public string LastPaymentDate { get; set; }
        public string OpenBalance { get; set; }
        public string OpenBalanceIND { get; set; }
        public string CurrentBalance { get; set; }
        public string CurrentBalanceIND { get; set; }
        public string OverdueAmount { get; set; }
        public string InstalmentAmount { get; set; }
        public string ArrearsPeriod { get; set; }
        public string RepaymentFrequencyDescription { get; set; }
        public string Terms { get; set; }
        public string StatusCode { get; set; }
        public string StatusCodeDesc { get; set; }
        public string IndustryType { get; set; }
        public string PaymentHistoryChartURL { get; set; }
        public string StatusDate { get; set; }
        public string ThirdPartyName { get; set; }
        public string ThirdPartySold { get; set; }
        public string ThirdPartySoldDescription { get; set; }
        public string JointLoanParticipants { get; set; }
        public string PaymentHistory { get; set; }
        public string PaymentHistoryStatus { get; set; }
        public string PaymentHistoryChart { get; set; }
        public string MonthEndDate { get; set; }
        public string DateCreated { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
