//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditinformation
    {
        public int ID { get; set; }
        public string SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string CreditSummaryChartURL { get; set; }
        public string DelphiScore { get; set; }
        public string DelphiScoreChartURL { get; set; }
        public string RiskColour { get; set; }
        public string FlagCount { get; set; }
        public string FlagDetails { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string TotalInstallmentAmountCPAAccounts_CompuScan { get; set; }
        public string TotalInstallmentAmountNLRAccounts_CompuScan { get; set; }
        public string TotalNumberCPAAccounts_CompuScan { get; set; }
        public string TotalNumberNLRAccounts_CompuScan { get; set; }
        public string TotalNumberActiveCPAAccounts_CompuScan { get; set; }
        public string TotalNumberActiveNLRAccounts_CompuScan { get; set; }
        public string TotalNumberClosedCPAAccounts_CompuScan { get; set; }
        public string TotalNumberClosedNLRAccounts_CompuScan { get; set; }
        public string typeOfSearch { get; set; }
    }
}
