//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datacount
    {
        public int ID { get; set; }
        public string SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string Accounts { get; set; }
        public string Enquiries { get; set; }
        public string Judgments { get; set; }
        public string Notices { get; set; }
        public string BankDefaults { get; set; }
        public string Defaults { get; set; }
        public string Collections { get; set; }
        public string Directors { get; set; }
        public string Addresses { get; set; }
        public string Telephones { get; set; }
        public string Occupants { get; set; }
        public string Employers { get; set; }
        public string TraceAlerts { get; set; }
        public string PaymentProfiles { get; set; }
        public string OwnEnquiries { get; set; }
        public string AdminOrders { get; set; }
        public string PossibleMatches { get; set; }
        public string DefiniteMatches { get; set; }
        public string Loans { get; set; }
        public string FraudAlerts { get; set; }
        public string Companies { get; set; }
        public string Properties { get; set; }
        public string Documents { get; set; }
        public string DemandLetters { get; set; }
        public string Trusts { get; set; }
        public string Bonds { get; set; }
        public string Deeds { get; set; }
        public string PublicDefaults { get; set; }
        public string NLRAccounts { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
