//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JCredDBContextEntities : DbContext
    {
        public JCredDBContextEntities()
            : base("name=JCredDBContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<orgcategory> orgcategories { get; set; }
        public virtual DbSet<orgregion> orgregions { get; set; }
        public virtual DbSet<orgtenant> orgtenants { get; set; }
        public virtual DbSet<orgtenantpriv> orgtenantprivs { get; set; }
        public virtual DbSet<orgunit> orgunits { get; set; }
        public virtual DbSet<orgunitprivmap> orgunitprivmaps { get; set; }
        public virtual DbSet<orgunituserprivmap> orgunituserprivmaps { get; set; }
        public virtual DbSet<aspnetpasshashhistory> aspnetpasshashhistories { get; set; }
        public virtual DbSet<aspnetuser> aspnetusers { get; set; }
        public virtual DbSet<C__efmigrationshistory> C__efmigrationshistory { get; set; }
        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<addresshistory> addresshistories { get; set; }
        public virtual DbSet<aspnetrole> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual DbSet<bank_preferences> bank_preferences { get; set; }
        public virtual DbSet<cca12months> cca12months { get; set; }
        public virtual DbSet<cca24months> cca24months { get; set; }
        public virtual DbSet<cca36months> cca36months { get; set; }
        public virtual DbSet<check_list> check_list { get; set; }
        public virtual DbSet<check> checks { get; set; }
        public virtual DbSet<compuscansearchhist> compuscansearchhists { get; set; }
        public virtual DbSet<consumerstatistic> consumerstatistics { get; set; }
        public virtual DbSet<contactinformation> contactinformations { get; set; }
        public virtual DbSet<cpa_accounts> cpa_accounts { get; set; }
        public virtual DbSet<creditinformation> creditinformations { get; set; }
        public virtual DbSet<datacount> datacounts { get; set; }
        public virtual DbSet<debtreviewstatu> debtreviewstatus { get; set; }
        public virtual DbSet<directorsummary> directorsummaries { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<emailhistory> emailhistories { get; set; }
        public virtual DbSet<employment_details> employment_details { get; set; }
        public virtual DbSet<employmenthistory> employmenthistories { get; set; }
        public virtual DbSet<enquiryhistory> enquiryhistories { get; set; }
        public virtual DbSet<fraudindicatorsummary> fraudindicatorsummaries { get; set; }
        public virtual DbSet<hangfireaggregatedcounter> hangfireaggregatedcounters { get; set; }
        public virtual DbSet<hangfirecounter> hangfirecounters { get; set; }
        public virtual DbSet<hangfirehash> hangfirehashes { get; set; }
        public virtual DbSet<hangfirejob> hangfirejobs { get; set; }
        public virtual DbSet<hangfirejobparameter> hangfirejobparameters { get; set; }
        public virtual DbSet<hangfirejobqueue> hangfirejobqueues { get; set; }
        public virtual DbSet<hangfirejobstate> hangfirejobstates { get; set; }
        public virtual DbSet<hangfirelist> hangfirelists { get; set; }
        public virtual DbSet<hangfireserver> hangfireservers { get; set; }
        public virtual DbSet<hangfireset> hangfiresets { get; set; }
        public virtual DbSet<hangfirestate> hangfirestates { get; set; }
        public virtual DbSet<homeaffairsinformation> homeaffairsinformations { get; set; }
        public virtual DbSet<internalenquiryhistory> internalenquiryhistories { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<nlr12months> nlr12months { get; set; }
        public virtual DbSet<nlr24months> nlr24months { get; set; }
        public virtual DbSet<nlr36months> nlr36months { get; set; }
        public virtual DbSet<nlrstat> nlrstats { get; set; }
        public virtual DbSet<personinformation> personinformations { get; set; }
        public virtual DbSet<propertiesbondinformation> propertiesbondinformations { get; set; }
        public virtual DbSet<propertiesbuyerinfo> propertiesbuyerinfoes { get; set; }
        public virtual DbSet<propertieserfinformation> propertieserfinformations { get; set; }
        public virtual DbSet<propertiesgeneralinformation> propertiesgeneralinformations { get; set; }
        public virtual DbSet<propertiesschemeinformation> propertiesschemeinformations { get; set; }
        public virtual DbSet<propertiessellerinformation> propertiessellerinformations { get; set; }
        public virtual DbSet<propertiessuburbinformation> propertiessuburbinformations { get; set; }
        public virtual DbSet<propertiestransferinformation> propertiestransferinformations { get; set; }
        public virtual DbSet<propertysummary> propertysummaries { get; set; }
        public virtual DbSet<search_history> search_history { get; set; }
        public virtual DbSet<searchresulttype> searchresulttypes { get; set; }
        public virtual DbSet<searchtype> searchtypes { get; set; }
        public virtual DbSet<syspriv> sysprivs { get; set; }
        public virtual DbSet<transunionsearchhistory> transunionsearchhistories { get; set; }
        public virtual DbSet<User> users { get; set; }
        public virtual DbSet<user1> users1 { get; set; }
        public virtual DbSet<xdssearchhistory> xdssearchhistories { get; set; }
        public virtual DbSet<hangfiredistributedlock> hangfiredistributedlocks { get; set; }
        public virtual DbSet<nlr_accounts> nlr_accounts { get; set; }
        public virtual DbSet<orgunitusermap> orgunitusermaps { get; set; }
        public virtual DbSet<searchhistory> searchhistories { get; set; }
        public virtual DbSet<creditdeclinereason> creditdeclinereasons { get; set; }
        public virtual DbSet<paymenthistoryaccountdetail> paymenthistoryaccountdetails { get; set; }
        public virtual DbSet<ccastat> ccastats { get; set; }
        public virtual DbSet<telephonehistory> telephonehistories { get; set; }
        public virtual DbSet<directorship> directorships { get; set; }
    
        public virtual int sp_purgehistorydata(Nullable<System.DateTime> cutOff_DateTime)
        {
            var cutOff_DateTimeParameter = cutOff_DateTime.HasValue ?
                new ObjectParameter("cutOff_DateTime", cutOff_DateTime) :
                new ObjectParameter("cutOff_DateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_purgehistorydata", cutOff_DateTimeParameter);
        }
    }
}
