//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class directorship
    {
        public int SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string DesignationCode { get; set; }
        public string AppointmentDate { get; set; }
        public string DirectorStatus { get; set; }
        public string DirectorStatusDate { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string CompanyStatus { get; set; }
        public string CompanyStatusCode { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public string CompanyRegistrationDate { get; set; }
        public string CompanyStartDate { get; set; }
        public string CompanyTaxNumber { get; set; }
        public string DirectorTypeCode { get; set; }
        public string DirectorType { get; set; }
        public string MemberSize { get; set; }
        public string MemberContribution { get; set; }
        public string MemberContributionType { get; set; }
        public string ResignationDate { get; set; }
    }
}
