//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class directorship
    {
        public int SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string Designation { get; set; }
        public string AppointmentDate { get; set; }
        public string PhysicalAddress { get; set; }
        public string TelephoneNumber { get; set; }
        public string DirectorStatus { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCategory { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
