//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class homeaffairsinformation
    {
        public int ID { get; set; }
        public string SearchToken { get; set; }
        public string Reference { get; set; }
        public Nullable<int> SearchID { get; set; }
        public string FirstName { get; set; }
        public string DeceasedDate { get; set; }
        public string IDVerified { get; set; }
        public string SurnameVerified { get; set; }
        public string Warnings { get; set; }
        public string DeceasedStatus { get; set; }
        public Nullable<sbyte> VerifiedStatus { get; set; }
        public Nullable<sbyte> InitialsVerified { get; set; }
        public string CauseOfDeath { get; set; }
        public string VerifiedDate { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
