//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personinformation
    {
        public int ID { get; set; }
        public string SearchToken { get; set; }
        public string Reference { get; set; }
        public Nullable<int> SearchID { get; set; }
        public string InformationDate { get; set; }
        public string PersonID { get; set; }
        public string Title { get; set; }
        public string DateOfBirth { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Fullname { get; set; }
        public string IDNumber { get; set; }
        public string IDNumber_Alternate { get; set; }
        public string PassportNumber { get; set; }
        public string Ref { get; set; }
        public string MaritalStatus { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string MiddleName1 { get; set; }
        public string MiddleName2 { get; set; }
        public string SpouseFirstName { get; set; }
        public string SpouseSurname { get; set; }
        public string NumberOfDependants { get; set; }
        public string Remarks { get; set; }
        public string CurrentEmployer { get; set; }
        public string VerificationStatus { get; set; }
        public Nullable<sbyte> HasProperties { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
