//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertiestransferinformation
    {
        public int SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string TransferID { get; set; }
        public string AttorneyFirmNumber { get; set; }
        public string AttorneyFileNumber { get; set; }
        public string TitleDeedFeeAmount { get; set; }
        public string TransferDate { get; set; }
        public string PurchaseDate { get; set; }
        public string PurchasePrice { get; set; }
        public string TitleDeedNumber { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
