//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertiesbuyerinfo
    {
        public int SearchToken { get; set; }
        public string Reference { get; set; }
        public string SearchID { get; set; }
        public string PersonTypeCode { get; set; }
        public string Fullname { get; set; }
        public string IDNumber { get; set; }
        public string MaritalStatus { get; set; }
        public string PropertySharePercentage { get; set; }
        public string HasProperties { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
