//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class search_history
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public System.DateTime application_date { get; set; }
        public string applicant_Fname { get; set; }
        public string applicant_Lname { get; set; }
        public string status { get; set; }
        public string id_Number { get; set; }
        public string account_user { get; set; }
        public string region { get; set; }
    }
}
