//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user1
    {
        public int uid { get; set; }
        public string date_added { get; set; }
        public string fullname { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string code { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public string org { get; set; }
        public string avatar { get; set; }
        public string cover { get; set; }
        public string logo { get; set; }
        public string dob { get; set; }
        public string gender { get; set; }
    }
}
