//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchworks.client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xdssearchhistory
    {
        public int ID { get; set; }
        public string searchID { get; set; }
        public string searchUserName { get; set; }
        public string reportDate { get; set; }
        public string reference { get; set; }
        public string searchToken { get; set; }
        public string callerModule { get; set; }
        public string dataSupplier { get; set; }
        public string searchType { get; set; }
        public string searchDescription { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string typeOfSearch { get; set; }
    }
}
